#!/bin/bash
set -eu

OUT_DIR="build/macos_debug"
ODIN_FLAGS=-debug

mkdir -p "$OUT_DIR"

odin run src/atlas-builder

odin build src -out:$OUT_DIR/game.bin

# copy assets
# cp -R assets $OUT_DIR

echo "build created in $OUT_DIR"

